### ISSUE TITLE
OS USAGE PROBABILITY

### ISSUE THREAD

**Issue by afifafifafifafifali** [SkyEng1neering/dalloc#3]
hi there , I'm making a os series and have interest in your project named as dalloc.

**Comment by SkyEng1neering** [comment]
Hi, it is licensed by apache 2.0 license, so feel free to use the project keeping copyright info in source files title and link to the original resource. If you'll find some bugs or decide to add some features fill free to create the issues or pull requests, i would be happy to collaborate
